### ISSUE TITLE
'Save Changes' should probably work without requiring input from the user

### ISSUE THREAD

**Issue by lekkas** [resin-io/pensieve#136]
Defaulting to some predefined message would be a nice-to-have, especially in cases where the fix is trivial (e.g. fixing a typo in a `Text` field)

See: https://www.flowdock.com/app/rulemotion/r-process/threads/dz3oz0WRuNRA5yeIqPW3-sR2PCL

**Comment by LucianBuzzo** [comment]
Each change should have a specific message. I'm against using a predefined commit message as it will become too easy to be creating a meaningless commit history. Even if the fix is trivial the commit message shouldn't be.

**Comment by alexandrosm** [comment]
Disagree as well. @lekkas is this a blocker for using for agendas?

**Comment by lekkas** [comment]
Quoting from the linked thread:

> I found that the modal that blocks the data entry/save flow makes the whole process more difficult and slow than it is with the current github wiki approach (which also is github backed, doesn't block and can automatically add a commit message)

> editing agenda items is not a one-off action. One might want to edit typos, add more tags, change the status, add more notes, actions etc. , I really don't see why, as a user, I should care about the commit message trail these actions leave

**Comment by lekkas** [comment]
To follow up from today's conversation, yes, I consider this a blocker for pensive adoption @alexandrosm @LucianBuzzo . To sum up, as a user, I don't want an extra step after saving, because it makes the process slower. Check the quoted text in the previous message for more context.

**Comment by sonyagreen** [comment]
I would like more discussion about this, to make sure having zero manual commit message is what we want for the scratchpad. Part of making sure the entries that are being added or changed correctly is checking the [wiki commit messages](https://github.com/resin-io/hq/wiki/Scratch-Pad/_history). Although an automated commit message shows what's changed, will it provide the kind of context needed for someone auditing recent changes of the scratchpad? @lekkas you and I talked about this idea this morning - what do you think? Would you be able to tell what commits to check based on the automated commit message?

**Comment by lekkas** [comment]
> Would you be able to tell what commits to check based on the automated commit message?

@sonyagreen definitely, check the commit history in https://github.com/resin-io/scratchpad/commits/master - @LucianBuzzo 's change is adding a very descriptive message like

> Edited entry "Test", changing the field "Signs and Symptoms"

and you can see the author.

So, in my opinion, this issue can be closed.

**Comment by sonyagreen** [comment]
It shows that the fields were edited and by whom, but it doesn't express how big of a change it was (typo vs rewrite). I'd guess many of the messages will look identical outside of the name of the entry, like *changing fields "GitHub issue", "Signs and Symptoms" and "Versions Affected"*.

**Comment by lekkas** [comment]
@sonyagreen Can you give a detailed description of how the Scratchpad audit workflow you envision will look like and why it absolutely needs a hand-written summary of how big the change was? If the auditor is expected to go through the commit history, he/she might as well check the diffs/updated entries.

I strongly believe that we should prioritize making the data entry process as frictionless as possible and refrain from making the process more difficult based on guesses of what problems the auditors might face in the future. Let's also take into account that we want to transfer the scratchpad from the wiki in the short term and in general, I think that for any usability tradeoffs like this we should lean/focus on the agent/data entry side and not on the auditor.

**Comment by sonyagreen** [comment]
This seems to boil down to the question if writing custom commit messages for scratchpad entries is worth the friction. @lekkas you outlined the friction, generally that a writing a commit message requires the author to spend more time with the entry than just writing it. 

If we look at GitHub's commit messages, they aren't optional, but they do auto-fill text for you. The GitHub workflow is a **lot** different than Pensieve -- like, you're able to add multiple files before committing. Even in the wiki you can preview before you save, and there's a cached autosave of some sort. So, this points to reducing friction while saving an entry.

Thinking about why to bother with commit messages at all, they aren't just documenting what changed - they document why something changed. That's what I think might be valuable to capture, because the 'why' isn't obvious even from scanning diffs. That would help whomever is auditing commit logs. If that's the only benefit, then as long as it doesn't become time inefficient the auditor  can figure out the 'why' commit by commit. There's one small question left - if writing a commit message serves other purposes -- like taking a minute to explain (to yourself as well as the rest of us) why you're updating an entry. Is that reflection helpful enough to be worth the friction?

One option would be to mimic GitHub - near the save button, offering an optional field for a change note, and assume that an author will add custom text if the edit is noteworthy. If not, the entry can use the automated commit message.

(For the scratchpad migration I think we can deal with the pain of commit messages as a one-time cost, or find a temporary way around it. I'm thinking about the features needed for daily use.)

**Comment by lekkas** [comment]
@sonyagreen , let's take a step back first, there are two separate issues mentioned in this thread:

- Two-step save flow with an unskippable modal that required a commit message. This was the reason why I opened this issue in the first place and it has been resolved by @LucianBuzzo in https://github.com/resin-io/pensieve/pull/157 (by the way, there's some interesting context in that PRs discussion that you might be interested in @sonyagreen). As such, I'm re-closing the issue. On a general note, let's leave it to the maintainer (in this case Lucian) to decide whether or not an issue should be re-opened.
- Commit messages are now completely automated and we're investigating whether this will cause issues during audits. This is a separate issue and we should continue the discussion in a separate thread. I've opened https://github.com/resin-io/pensieve/issues/173 for this reason, so let's take it from there.
